language: python
addons:
  chrome: stable
python:
  - "2.7"
  - "3.5"
env:
  global:
    - aws_id="AKIAJDYW3E3ERXZTUFDA"
    - aws_region="us-west-2"
  matrix:
    - SYMPYVERSION=""
    - SYMPYVERSION="==1.2"
    - SYMPYVERSION="==1.1.1"
matrix:
  include:
    - python: "2.7"
      env: web=true
before_install:
  - mkdir ~/.aws
  - echo "[default]]\naws_access_key_id = $aws_id\naws_secret_access_key = $aws_key" > ~/.aws/credentials
  - echo "[default]]\nregion = $aws_region" > ~/.aws/config
install:
  - if [ $web = true ]; then
    pip install piexif selenium awscli;
    cd web;
    wget https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip;
    unzip chromedriver_linux64.zip;
    PATH=$PATH:$(pwd);
    make sdk;
    else
    pip install sympy$SYMPYVERSION;
    fi;
script:
  - if [ $web = true ]; then
    make test;
    else
    cd python;
    python TestSuite.py;
    fi;
secure: "aFBhL5Gni48cIGv3x+yE1xT0P+/OraB49DdXftk+SNWkD0ylMBwUV2k8uji0og38nGPrq+iVcOyVEAp421cM2oO6N3cGQDUSl+8l3c4UG/tF2mg6URS+EDS1R49sULOypnahwUmtKgeCv3ZbupvoAlpAgslDscfjvoseFXKcQPjqrn+v28Bbg1RS8UrEyf/XQPdDy6LPw23kure4mTRNOX1OC4sTB4si1K34Frb4cEsjP4/xjXNO8KvFGMcvzS9rj6RWrL68JlAXDzPFSL6z4vbOwk/MJHkHjo8xGcUGPahufs6dG/scXD9Se/tnPMA5C2rTLIutVt2xUe9mQiVPCFY3D+zJLbkPFoDTrV+8Ja1EPzUbjfrR4uk3TPMLcK+fWQVcIfmJ5exvzC2MgeP5yA6pbCYj6Q7DXD1X5wnEBwmZLwAYsE0SfmdPG+Yues4VYVQ+2JiWPv98HUVflm6bFVCndPw+x7RmF8RX5yruP+i2iJdmFd3CTvd+EGDL6T2TDMNfkdTz/7Mvo77FzCkHmYhLEPsaudP0l8KAGC9qIi/Dr5Ra2pe3ESKxfLwCw/dhFdRnNbizpl2yFzKzIl/Q36e4EP6iaCAwsfLy5/fvlQodPADH4UYMJjWZTGCz59o8cTDKsJ017GYybgtZ2edr3vR4Qq9MNj4PKQ2ugCh3YtI="
