language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
env:
  - SV=""
  - SV="==1.1.1"
  - SV="==1.1"
  - SV="==1.0"
  - SV="==0.7.6.1"
  - SV="==0.7.6"
  - SV="==0.7.5"
  - SV="==0.7.4.1"
  - SV="==0.7.4"
  - SV="==0.7.3"
  - SV="==0.7.2"
  - SV="==0.7.1"
  - SV="==0.7.0"
  - SV="==0.6.6"
  - SV="==0.6.5"
  - SV="==0.6.4"
  - SV="==0.6.3"
  - SV="==0.6.2"
  - SV="==0.6.1"
  - SV="==0.6.0"
  - SV="==0.5.15"
  - SV="==0.5.13-hg"
install:
  - pip install sympy$SV
script:
  - cd python
  - python TestSuite.py
