language: python
addons:
  chrome: stable
python:
  - "2.7"
  - "3.5"
env:
  - SYMPYVERSION=""
  - SYMPYVERSION="==1.2"
  - SYMPYVERSION="==1.1.1"
matrix:
  include:
    - python: "2.7"
      env: web=true
install:
  - if [ $web = true ]; then
    pip install piexif selenium;
    cd web;
    wget https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip;
    unzip chromedriver_linux64.zip;
    PATH=$PATH:$(pwd);
    else
    pip install sympy$SYMPYVERSION;
    fi;
script:
  - if [ $web = true ]; then
    make test;
    else
    cd python;
    python TestSuite.py;
    fi;
