AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A web application to find State Space models given the elemental and constraint equations.
Resources:
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ${stack}
      Handler: StateMintLambda.handler
      Runtime: python2.7
      CodeUri: lambda.zip
      Description: The Lambda function for StateMint.
      MemorySize: 768
      Timeout: 30
      Events:
        Http:
          Type: Api
          Properties:
            Path: /StateMint
            Method: post
            RestApiId: !Ref API
  API:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: StateMint
      StageName: StateMint
      DefinitionUri: api.yml
Outputs:
  ApiId:
    Value: !Ref API
