AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A web application to find State Space models given the elemental and constraint equations.
Resources:
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Statum
      Handler: StateModelLambda.handler
      Runtime: python2.7
      CodeUri: lambda.zip
      Description: The Lambda function for Statum.
      MemorySize: 768
      Timeout: 10
      Events:
        Http:
          Type: Api
          Properties:
            Path: /Statum
            Method: post
            RestApiId: !Ref API
  API:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: Statum
      StageName: Stage2
      DefinitionUri: api.yml
Outputs:
  ApiId:
    Value: !Ref API
