AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A web application to find State Space models given the elemental and constraint equations.
Resources:
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: StateModelRnDdev
      Handler: StateModelLambda.handler
      Runtime: python2.7
      CodeUri: lambda.zip
      Description: The Lambda function for StateModelRnD.
      MemorySize: 768
      Timeout: 10
      Events:
        API:
          Type: Api
          Properties:
            Path: /StateModelRnD
            Method: post
  API:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: StateModelRnDdev
      StageName: Stage2
      DefinitionUri: api.yml
      Variables:
        LambdaFunctionName: !Ref LambdaFunction
        Region: !Sub ${AWS::Region}
        AccountId: !Sub ${AWS::AccountId}
Outputs:
  ApiId:
    Value: !Ref API
